site_name: "Gio's Skyrim: A Wabbajack Compilation"
site_author: Gio
site_url: https://gio-gianny.github.io/gio_skyrim_stock_game/
repo_url: https://github.com/gio-gianny/gio_skyrim_stock_game
copyright: Copyright &copy; 2025 Gio

theme:
  logo: images/logo.svg
  favicon: images/favicon.ico
  name: material
  features:
    - navigation.tabs  # show navigation tabs on top
    - navigation.tabs.sticky  # lock the navigation tabs on top, so they are always visible
    - navigation.expand  # exapand all left sidebar sections by default
    - toc.integrate  # show toc in the left sidebar
    - navigation.top  # show a back-to-top button when starting to scroll up
    - navigation.footer  # include links to the previous and next page
    - content.code.copy  # add copy-to-clipboard to code blocks
  palette:
    scheme: slate
    primary: custom

extra:
  generator: false  # hide the "Made with Material for MkDocs" notice from the footer

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

plugins:
  - awesome-nav
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: project_info
          class: project_info
          template: templates/project_info.jinja
          format: !!python/name:mkdocs_custom_yaml_fences.formatter
        - name: mo2_mods
          class: mo2_mods
          template: templates/mo2_mods.jinja
          format: !!python/name:mkdocs_custom_yaml_fences.formatter
        - name: mo2_launcher
          class: mo2_launcher
          template: templates/mo2_launcher.jinja
          format: !!python/name:mkdocs_custom_yaml_fences.formatter
