site_name: "Gio's Skyrim: A Wabbajack Compilation"
site_author: Gio
site_url: https://gio-gianny.github.io/gio_skyrim_stock_game/
repo_url: https://github.com/gio-gianny/gio_skyrim_stock_game
copyright: Copyright &copy; 2025 Gio

theme:
  logo: images/logo.svg
  favicon: images/favicon.ico
  name: material
  features:
    # - navigation.tabs  # show navigation tabs on top
    # - navigation.tabs.sticky  # lock the navigation tabs on top, so they are always visible
    # - navigation.expand  # exapand all left sidebar sections by default
    # - toc.integrate  # show toc in the left sidebar
    - navigation.top  # show a back-to-top button when starting to scroll up
    - navigation.footer  # include links to the previous and next page
    - content.code.copy  # add copy-to-clipboard to code blocks
    # - navigation.sections  # rendered top-level sections as groups in the sidebar, for viewports above 1220px
    - navigation.indexes  # attach the index.md to the main section
  palette:
    scheme: slate
    primary: custom

extra:
  generator: false  # hide the "Made with Material for MkDocs" notice from the footer

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

plugins:
  - awesome-nav
  # Markdown includer plugin
  # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - include-markdown
  - search
  - tags

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - meta
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: fomod_settings
          class: fomod_settings
          template: templates/fomod_settings.j2
          format: !!python/name:mkdocs_custom_yaml_fences.formatter
        - name: mo2_mods
          class: mo2_mods
          template: templates/mo2_mods.j2
          format: !!python/name:mkdocs_custom_yaml_fences.formatter
        - name: mo2_launcher
          class: mo2_launcher
          template: templates/mo2_launcher.j2
          format: !!python/name:mkdocs_custom_yaml_fences.formatter
        - name: project_info
          class: project_info
          template: templates/project_info.j2
          format: !!python/name:mkdocs_custom_yaml_fences.formatter
  - pymdownx.tasklist:
      custom_checkbox: true
