append_unmatched: true
nav:
  - Home: README.md
  - Compile:
    - General notes: general_notes/
    - MO2: mo2/
    - MO2 plugins: mo2_plugins/
    - Tools: tools/
    - Mods: mods/
    - Wabbajack: wabbajack/
  - Playing: playing/
  - Rejected: rejected/
  - Credits: credits.md
