append_unmatched: true
nav:
  - Home: README.md
  - Users: users.md
  - General notes: general_notes/
  - MO2: mo2/
  - MO2 plugins: mo2_plugins/
  - Tools: tools/
  - nexus: mods/
  - Wabbajack: wabbajack/
  - Credits: credits.md
